
INSERT INTO identitystore_attribute (key_name, name, description, key_type, certifiable, pivot, key_weight) VALUES
('gender', 'Genre', '0:Non défini /  1:Homme / 2:Femme', 0, 1, 1, 3),
('family_name', 'Nom de famille de naissance', '', 0, 1, 1, 18),
('preferred_username', 'Nom usuel','', 0, 0, 0, 15),
('first_name', 'Prénoms', 'Prénoms usuels', 0, 1, 1, 10),
('birthdate', 'Date de naissance', 'au format DD/MM/YYYY', 0, 1, 1, 17),
('birthplace_code', 'Code INSEE commune de naissance', '', 0, 1, 1, 5),
('birthcountry_code', 'Code INSEE pays de naissance', '', 0, 1, 1, 3),
('birthplace', 'Libellé INSEE commune de naissance', '', 0, 1, 0, 5),
('birthcountry', 'Libellé INSEE pays de naissance', '', 0, 1, 0, 3),
('email', 'Email', '', 0, 1, 0, 20),
('login', 'Login de connexion (email utilisé, 0)', '', 0, 1, 0, 20),
('mobile_phone', 'Téléphone portable', 'Réservé pour l''envoi de SMS', 0, 1, 0, 0),
('fixed_phone', 'Téléphone fixe', '',0, 0, 0, 0),
('address', 'Adresse', '', 0, 1, 0, 0),
('address_detail', 'Complément d''adresse', '', 0, 1, 0, 0),
('address_postal_code','Code postal','Champ d''adresse : code postal',0, 1, 0, 0),
('address_city','Ville','Champ d''adresse : ville',0, 1, 0, 0),
('fc_key' , '(FC, 0) Key' , 'Format Pivot FranceConnect - Key' , 0, 0, 0, 0);
